name 'elkhem-node'
maintainer 'Rich Bywater'
maintainer_email 'r@faultloop.co.uk'
license 'GNU GENERAL PUBLIC LICENSE'
description 'Installs/Configures elkhem-node'
long_description 'Installs/Configures elkhem-node'
version '0.5.0'
chef_version '>= 15.0'
